book/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns =[
    path("", views.index, name = "index"),
    path("<int:pk>/", views.show, name = "show"),
    path("add/", views.add, name = 'add'),
    path("<int:pk>/edit/", views.edit, name = 'edit'),
    path("<int:pk>/delete/", views.delete, name = 'delete'),
]

web_1210/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from book import views as book_views
from django.shortcuts import redirect

admin.site.site_title = 'Book 網站管理'
admin.site.site_header = 'Book 管理' 

# def root(request):
#     return redirect('books-index')

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    # path('', views.root),
    # path("<str:name>/", views.hello),
    # path("s/<int:number>/", views.s),
    # path("l/<int:num1>/<int:num2>/", views.l),

    path('', lambda request: redirect('books:index'), name='root'),
    path('books/', include('book.urls')),
#     path("books/", book_views.index, name = "books-index"),
#     path("books/<int:pk>/", book_views.show, name = "books-show"),
#     path("books/add/", book_views.add, name = 'books-add'),
#     path("books/<int:pk>/edit/", book_views.edit, name = 'books-edit'),
#     path("books/<int:pk>/delete/", book_views.delete, name = 'books-delete'),
 ]

book/models.py
from django.db import models

class Book(models.Model):
    name = models.CharField('書名', max_length = 20)
    price = models.PositiveIntegerField('價格')
    introduction = models.TextField('簡介')

    def __str__(self):
        return "{},({})".format(self.name, self.price)
        

book/forms.py
from django import forms

from .models import Book


# class BookForm(forms.Form):
#     name = forms.CharField(max_length=20, label="書名: ")
#     price = forms.IntegerField(min_value=1, label="價格: ")
#     introduction = forms.CharField(widget=forms.Textarea(), label='簡介')

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='你確定要刪除嗎?')

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from .forms import BookForm, DeleteConfirmForm
from .models import Book

def index(request):
    books = Book.objects.all()
    return render(request, "books/index.html",{'books': books})

def show(request, pk):
    # try:
    #     book = Book.objects.get(pk=pk)
    # except Exception:
    #     raise Http404
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'books/show.html', {'book':book})

def add(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()         
        messages.success(request, '新增成功')
        return redirect('books:index')

    return render(request, "books/add.html", {'form': form})

def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance= book)
    if form.is_valid():
        form.save()         
        messages.success(request, '更新成功')
        return redirect('books:index')

    return render(request, "books/edit.html", {'form': form})

def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        book.delete() 
        messages.success(request, '刪除成功')
        return redirect('books:index')

    return render(request, "books/delete.html", {'form': form})

web_1210/views.py
from django.http import HttpResponse
from django.shortcuts import render

def root(request):
    name = request.GET.get("name", "guest")
    return HttpResponse("hi, {}".format(name))

def hello(request, name):
    return HttpResponse("hi,{}".format(name))

def s(request, number):
    return HttpResponse(number **2)

def l(request, num1, num2):
    # if num1 < num2:
    #     _list = range(num1, num2+1)
    # else:
    #     _list = reversed(range(num2, num1+1))

    _list = range(10, 0, -1)

    step = -1 if num1>num2 else 1
    _list = range(num1, num2+step, step)
    
    return render(request, "h.html", {"list": _list})

templates/books/add.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block main %}
  <div class="row">
    <div class="col">
        <h2>新增書籍</h2>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %} 
            <button type="submit" class="btn btn-outline-info float-right">send</button>
        </form>
    </div>
  </div>
{% endblock %}

templates/books/delete.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col">
        <h2>刪除書籍</h2>
        <hr>
        {% include "share/form.html" %}
    </div>
  </div>
{% endblock %}

templates/books/edit.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col">
        <h2>更新書籍</h2>
        <hr>
        {% include "share/form.html" %}
    </div>
  </div>
{% endblock %}

templates/books/index.html
{% extends 'layout.html' %}

{% block main %}
<div class="rol">
 <div class="col">
<a href="{% url 'books:add' %}" class="btn btn-outline-info float-right">Add book</a>
 <h2>Book List</h2>
   <hr> 
    <table>
      <thead>
        <tr>
            <th>#</th>
            <th>name</th>
            <th>price</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
            <td>{{ book.id }}</td>
            <td><a href="{% url 'books:show' book.id %}">{{book.name}}</a></td>
            <td>{{book.price}}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan ="3" class = "text-center">No books!!!</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

templates/books/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block main %}
    <h2>{{ book.id }} {{ book.name }}</h2>
    <hr>
    <p>Name: {{ book.name }}</p>
    <p>Price: {{ book.price }}</p>    
    <p>Introtruction: {{ book.introtruction }}</p>
    <a href="{% url 'books:index' %}" class="btn btn-primary"><< Back</a>
    <a href="{% url 'books:edit' book.id %}" class="btn btn-info">edit</a>
    <a href="{% url 'books:delete' book.id %}" class="btn btn-info">Delete</a>
    {% endblock %}
</body>
</html>

templates/h.html
<ul>
    {% for i in list %}
        <li>{{ i }}</li>
    {% endfor %}
</ul>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Store</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

{% load bootstrap4 %}

<body>
    <div class="container my-3">
        {% bootstrap_messages %}
        {% block main %}{% endblock %}
    </div>
</body>

</html>

templates/share/form.html
{% load bootstrap4 %}

<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %} 
<button type="submit" class="btn btn-outline-info float-right">send</button>
</form>